title: Deerlin Theme
tagline: Deerlin is a theme for Jekyll.
description: Deerlin is a theme developed by Nashira Deer to be used in his websites that uses Jekyll.
footer: The favicon used in this website belongs to Nashira Deer. All rights reserved.
theme-color: '#a914ee'
google-analytics: G-J6261MBX9H
exclude: [ SECURITY.md ]
navbar:
  - name: Home
    url: /
  - name: Another Page
    url: /another-page
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
noscript: Your browser has JavaScript disabled and you may experience issues in the navbar because of this. 
deprecated-features: 
  enabled: false
  logomark:
  source-sans-pro: false