title: Deerlin Theme
description: Deerlin is a theme developed by Nashira Deer to be used in his websites that uses Jekyll.
google-analytics:
logomark:
navbar:
  - name: Home
    url: /
  - name: Another Page
    url: /another-page
