title: Deerlin Theme
tagline: Deerlin is a theme for Jekyll.
description: Deerlin is a theme developed by Nashira Deer to be used in his websites that uses Jekyll.
theme-color: '#a914ee'
google-analytics:
logomark:
navbar:
  - name: Home
    url: /
  - name: Another Page
    url: /another-page
plugins:
  - jekyll-seo-tag